Añade planificación, closes #11
Torchu/flixbuff pull request #12
Opened 2022-07-09 15:19 UTC by Torchu

Avanza con la planificación del proyecto, a falta de incluir imágenes que apoyen al texto cuando se avance con el código.

2022-07-21 12:41 UTC, JJ requested changes
Aquí sí creo que hay algunas cosas que podrías hacer mejor, o aclarar.

2022-07-21 12:41 UTC, JJ commented on doc/apendices/A_personas.tex
> +      \item Salir de fiesta.
Recuerda que las personas diferentes tienen diferentes requisitos; si son simplemente gustos diferentes no creo que te hagan falta. Las personas se necesitan para justificar, por ejemplo, los tipos de dispositivo donde se va a ejecutar la aplicación.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para empezar a desarrollar la solución al problema, primero hay que establecer la metodología de su desarrollo y control de calidad.
Quizás deberías invertir esto; la metodología precede a la planificación. Si es waterfall, vas a planificar todo desde el principio; si es ágil, prácticamente sólo los primeros hitos o el hito siguiente.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Las metodologías ágiles más utilizadas son Kanban y Scrum. Scrum se basa en ciclos cortos de trabajo en los que cada X semanas, el cliente recibe un avance en el código de acuerdo a una previa planif
Ágil no es una metodología, es una mentalidad para elegir metodologías. Las que mencionas son metodologías para estimar el trabajo necesario y priorizar las tareas, respectivamente.
También: cita el manifiesto. Recuerda, muchas citas.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para la transparencia y visualización del proyecto a lo largo de sus diferentes fases, debemos de poder acceder a estados anteriores en su desarrollo. Para ello, utilizaremos Git, un sistema de contr
Para que lo siga ¿quién? Tendrás que hablar de los "stakeholders" (vamos, yo solo).

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Historias de Usuario}. Requerimientos propuestos por los usuarios de la aplicación.
Enlázalas

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Issues}. Fallos en la aplicación que han de ser resueltos.
No siempre son fallos. Son problemas a resolver.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Tareas para el desarrollador}. Pequeñas tareas que no representan una funcionalidad como tal.
Di como las vas a hacer, si como parte de un issue o directamente como issues diferentes.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para asegurar la calidad del proyecto, se ha utilizado integración continua a través de las ya mencionadas antes GitHub Actions.\\
REcuerda que #8 no tiene por qué conocer términos como integración continua, y si me apuras, ni GitHub.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Cada vez que se sube nuevo código a una rama del repositorio, se realiza un análisis estático del código por medio de \textit{linters} y se lanzan unos tests que aseguran que la funcionalidad del cód
Igual que arriba.

2022-07-21 12:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> -\section{Seguimiento del desarrollo}
Esto tienes que ponerlo, y empezar a hacerlo desde el principio.

2022-07-23 16:44 UTC, Torchu commented on doc/apendices/A_personas.tex
> +      \item Salir de fiesta.
Puedo poner que una persona quizá utilice la aplicación desde el móvil, pero dejar el hacer una app móvil (o adaptarla a vista móvil) como trabajo futuro? Por la fecha en la que estamos no creo que me de tiempo a montar un front-end con flutter o algún otro framework de smartphone. Si no se complica mucho, intentaré hacer que la vista responsive de la web sea decente.

2022-07-23 16:52 UTC, Torchu commented on doc/apendices/A_personas.tex
> +      \item Salir de fiesta.
He cambiado los apartados de cosas que le gustan/no le gustan por uno sobre su relación con la tecnología en la que se justifica qué dispositivo usaría cada usuario al utilizar la aplicación.

2022-07-23 16:58 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> -\section{Seguimiento del desarrollo}
Si te refieres al seguimiento del desarrollo, sale como borrado porque ahora es una subsección dentro de la Metodología utilizada.

2022-07-23 17:13 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Issues}. Fallos en la aplicación que han de ser resueltos.
Fixed

2022-07-23 17:13 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Tareas para el desarrollador}. Pequeñas tareas que no representan una funcionalidad como tal.
Fixed

2022-07-23 17:34 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +Para asegurar la calidad del proyecto, se ha utilizado integración continua a través de las ya mencionadas antes GitHub Actions.\\
Me he explayado algo más en esta sección explicando un poco mejor lo que es la integración continua, los linters, los pipelines, etc.

2022-07-23 17:37 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Historias de Usuario}. Requerimientos propuestos por los usuarios de la aplicación.
He incluido un párrafo explicando que cada tipo de tarea tiene una etiqueta asociada a sus issues. ¿Es suficiente con esto, o pongo en cada título un enlace a las issues con esa etiqueta?

2022-07-23 17:42 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +Para la transparencia y visualización del proyecto a lo largo de sus diferentes fases, debemos de poder acceder a estados anteriores en su desarrollo. Para ello, utilizaremos Git, un sistema de contr
He añadido un párrafo diciendo quién es el objetivo del seguimiento, pero el decir que tú eres el único stakeholder quedaba un poco raro, así que no he especificado quién. Lo he dejado como "personas interesadas". Que quién sabe, si anuncio lo que estoy haciendo, quizá no seas tú el único jajaja.

2022-07-23 17:44 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +Para empezar a desarrollar la solución al problema, primero hay que establecer la metodología de su desarrollo y control de calidad.
No entiendo a qué te refieres con "invertir esto". La metodología precede a la planificación, por eso mismo pone que lo primero es establecer la metodología de desarrollo.

2022-07-23 17:56 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +Las metodologías ágiles más utilizadas son Kanban y Scrum. Scrum se basa en ciclos cortos de trabajo en los que cada X semanas, el cliente recibe un avance en el código de acuerdo a una previa planif
He añadido citas

2022-07-24 08:20 UTC, JJ commented on doc/apendices/A_personas.tex
> +      \item Salir de fiesta.
Si. El producto final se hará cuando se pueda, pero en general, si no puedes cumplir los requisitos de una *persona* es mejor que no la incluyas, salvo que haya productos intermedios que también puedan ser usados por otra. Por ejemplo, un API REST puede ser usado por diferentes personas eventualmente.

2022-07-24 08:49 UTC, JJ requested changes
Los cambios solicitados son sobre todo por justificar y documentar todas las deciciones técnicas. Un TFG es el conjunto de decisiones técnicas que se hayan tomado (y lo que se haya aprendido con ellas).

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +    \item \textbf{Historias de Usuario}. Requerimientos propuestos por los usuarios de la aplicación.
Mejor un enlace, que se vea.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +% Introducir imagen cuando avances con alguna HU
En general estos comentarios no me hacen mucha gracia; en un PR "normal" te diría que abrieras un issue. Los comentarios tienen cierta tendencia a olvidarse, y puedes abrir un issue con referencia a una línea específica en el código.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +TDD\cite{TDD}.\\
TDD dice que las pruebas van primero; una vez más, si no lo usas *de verdad* no lo pongas, y si lo usas, documéntalo, por ejemplo mostrando cómo escribiste los tests antes que el código. Si simplemente tienes tests, es algo que te pide el manifiesto ágil.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Además del desarrollo guiado por pruebas, se han configurado una serie de \textit{linters}, unas herramientas que
Justifícalo también con el manifiesto ágil.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Finalmente, se ha incluido un \textit{script} que comprueba la ortografía de toda la documentación del proyecto.\\
Todo lo que vaya en el repo tiene que justificarse con una HU; en este caso la HU es la del tribunal, que es secreta, pero puedes añadir otra no secreta que sea del tutor.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +La integración continua es una metodología de trabajo que se basa en realizar integraciones frecuentes del código y
Y pedida por uno de los principios del manifiesto ágil.

2022-07-24 08:49 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para este proyecto, se han configurado las \textit{pipelines} con la herramienta GitHub Actions. Se ha escogido esta
Recuerda que las decisiones técnicas tienes primero que contextualizar (por qué quiero hacer esto, qué es lo que hay), poner especificaciones, y luego justificar la decisión en base a estas.
En este caso, Github Actions está bien, pero también tienes Azure Pipelines y una docena de otras opciones, como CircleCI y demás. Tanto elegir esta como elegir una sola (y no, pongamos, dos) tienes que justificarlo.

2022-07-24 09:04 UTC, JJ requested changes
Principal problema, "ágil" no es una metodología ni conjunto de metodologías. El resto son cosas menores (nits)

2022-07-24 09:04 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Todas las tareas estarán asociadas a una issue diferente y tendrán una etiqueta acorde a su tipo.
Indica que todo cambio en el repo tiene que hacerse cumpliendo una tarea.

2022-07-24 09:04 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +serán ellos quienes protagonicen las historias de usuario. Ver \autoref{chap:personas}.\\
Algunos posibles miembros del tribunal piensan que sólo se usan "personas" para diseño de UI. Aclara que se trata en general de una metodología para diseño de producto en general (y añade cita, ya la tienes en la biblio)

2022-07-24 14:11 UTC, Torchu commented on doc/apendices/A_personas.tex
> +      \item Salir de fiesta.
Okey. Esa _persona_ tiene más requisitos, por lo que no veo mal el dejarla y plantear el requisito móvil como parte de "trabajos futuros".

2022-07-24 14:22 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +TDD\cite{TDD}.\\
Tanto esto como lo anterior lo dejo con comentarios para completar cuando avance y lo recojo en una issue para que no se pierda

2022-07-24 14:52 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +Finalmente, se ha incluido un \textit{script} que comprueba la ortografía de toda la documentación del proyecto.\\
En mi cabeza, la revisión ortográfica es un linter igual que el que voy a configurar en python, por lo que para mí, tendría la misma justificación.

2022-07-24 16:08 UTC, Torchu commented on doc/secciones/04_planificacion.tex
> +serán ellos quienes protagonicen las historias de usuario. Ver \autoref{chap:personas}.\\
No está la cita ya añadida con el `\cite{}` o a qué te refieres?

2022-07-24 16:15 UTC, Torchu commented
He tratado de resolver todos los comentarios y en los que no, he respondido al comentario.

2022-07-25 16:31 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para empezar a desarrollar la solución al problema, primero hay que establecer la metodología de su desarrollo y control de calidad.
La metodología establece la planificación, no al revés. Estás poniendo la metodología en el apartado planificación. Si lo precede, lo precede, así que debe ir antes.

2022-07-25 16:33 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Finalmente, se ha incluido un \textit{script} que comprueba la ortografía de toda la documentación del proyecto.\\
Correcto, es calidad del producto, pero el *cliente* del producto es diferente, así que conviene que lo menciones y referencies.

2022-07-25 16:34 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +serán ellos quienes protagonicen las historias de usuario. Ver \autoref{chap:personas}.\\
Cita para que entiendan que se usa para diseño de productos, por ejemplo en lean startups y cosas así, no sólo para diseño de interfaz de usuario.

2022-07-25 16:41 UTC, JJ approved these changes
OK, esto ya rula. Algunos cambios antes de fusionar, o posteriormente, como veas.

2022-07-25 16:41 UTC, JJ commented on doc/apendices/A_personas.tex
> +    \item Suele usar su portatil para su afición de escritor. Se siente más cómodo que con el teléfono móvil.
typo. ¿Cómo no lo ha pillado el spell checker? ¿No están incluidos los apéndices?

2022-07-25 16:41 UTC, JJ commented on doc/apendices/A_personas.tex
> +    \item Suele usar su portatil para su afición de escritor. Se siente más cómodo que con el teléfono móvil.
Abierto #17

2022-07-25 16:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +control de calidad.\\
Sigo pensando lo mismo, la planificación es parte de la metodología, no al revés. Quizás el título sería mejor "Metodología y planificación" O simplemetne metodología, que también incluye planificación.

2022-07-25 16:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +Para el desarrollo del proyecto, tenía claro que quería utilizar una metodología basada en los principios del
Si el título cambia a "Metodología", esto sería "Principios metodológicos", o "principios para el desarrollo".

2022-07-25 16:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +% Son la infraestructura, el modelo de datos, el servicio de back y ambos front-end
Recuerda que los PMVs son acumulativos; el modelo de datos tiene que incluir la infraestructura y así sucesivamente.

2022-07-25 16:41 UTC, JJ commented on doc/secciones/04_planificacion.tex
> +TDD\cite{TDD}.\\
Pero asegúrate que estás usando de verdad TDD :-)

2022-07-26 11:24 UTC, Torchu commented
Pues pusheado con los cambios pertinentes. Lo del spell-checker lo haré en una nueva rama y lo del TDD, ya puedes ver la rama en la que configuro el lint y los tests para empezar con ello.

2022-07-26 11:27 UTC, merged