Creates data models
Torchu/flixbuff pull request #48
Opened 2022-08-27 16:46 UTC by Torchu

- Crea los modelos de datos básicos para las HU #35 y #36 y añade tests para la clase Review, ya que es la única con más lógica.
- Documenta todas las decisiones técnicas realizadas.
- Cambia la configuración de poetry para que al lanzarse desde la carpeta api, reconozca los módulos de la aplicación sin necesidad de añadir `api.` al import. (En el despliegue del back-end, api será la carpeta raíz por lo que estaría bien evitar tener que importar los modulos con `api.` como prefijo.

2022-08-28 17:17 UTC, JJ commented
Siempre es conveniente que crees issues intermedios que planteen los problemas específicos de cada una de las partes del modelo. Volvemos a lo mismo: ¿qué hago? ¿Lo hago bien? Un solo PR que directamente plantee código va a ser complicado de evaluar, sobre todo porque no tienes el segundo criterio. Los HUs no pueden tener detalles de implementación porque siempre están en el dominio del problema.

2022-08-28 17:25 UTC, JJ requested changes
Sólo te he comentado una pequeña parte, pero tenemos otra vez una serie de problemas metodológicos. Tienes que tener muy en cuenta qué es la estructura de datos, qué problema resuelve, cómo la vamos a usar, quién la va a controlar a la hora de diseñarla. Y todo eso tienes que desarrollarlo en una serie de issues. Nada de lo que pongas es obvio, ni se deduce de forma directa de la historia de usuario, como te he comentado en línea.

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +class ShowInfo:
Este es un ejemplo clásico de lo que ocurre cuando no planteas el problema en un issue.
El problema que plantea un show es:
* Cómo identificarlo de forma única.
* Cómo tener en cuenta que un show tiene una serie de temporadas.
* Si la información del show va a ser inmutable o no.

En general, debes plantear los problemas que se deduzcan de la historia de usuario. Se añade el código que resuelva ese problema; no se puede añadir nunca código refiriéndose directamente a una HU.

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +        self.season_id = season_id
Dices que representa "show info", sin embargo, en realidad representa información ¿de una sola temporada? ¿Vas a usar diferentes instancias para diferentes temporadas?

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +        self.season_name = season_name
¿Necesitas identificar temporadas de forma única? Si es así, ¿necesitas *nombre* _y_ *id*?

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +    def __init__(self, show_id: int, show_name: str, season_id: int, season_name: str) -> None:
Si el show_id es un _int_ ¿quién garantiza que vaya a ser único?

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +class ReviewerInfo:
¿Lo necesitas en este hito?

2022-08-28 17:25 UTC, JJ commented on api/models/review.py
> +        self.username = username
Si el username es único, ¿por qué necesitas el ID?

2022-08-28 18:19 UTC, Torchu commented on api/models/review.py
> +    def __init__(self, show_id: int, show_name: str, season_id: int, season_name: str) -> None:
¿Cómo puedo garantizar que sea único sin tener persistencia de datos?

2022-08-28 18:20 UTC, Torchu commented
Excepto por lo que he respondido, voy a plantear una serie de issues intermedias que definan bien lo que tiene que tener cada modelo.

2022-08-29 07:04 UTC, JJ commented on api/models/review.py
> +    def __init__(self, show_id: int, show_name: str, season_id: int, season_name: str) -> None:
Usando UUID, por ejemplo.

2022-08-29 10:56 UTC, Torchu commented
Pues, he creado 3 issues #49, #50 y #51 en los que especifico qué deben llevar los modelos. No he incluido identificadores ya que eso hasta que se plantee la persistencia no sería necesario. Como he puesto en telegram, no sé si la idea era hacer un PR por cada modelo, de momento sigo con este PR ya que está hecho.

2022-08-29 12:14 UTC, JJ commented
Hombre, habría sido interesante que hicieras PRs a esta rama. Pero ya lo has hecho así, a ver qué pasa.

2022-09-01 16:20 UTC, merged